
import React, { createContext, useContext, useState, useEffect } from 'react';
import { supabase } from '../lib/supabase';
import { useAuth } from './AuthContext';

type Language = 'pt-BR' | 'en-US' | 'es-ES';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
    'pt-BR': {
        // Navigation
        'nav.dashboard': 'Dashboard',
        'nav.athletes': 'Atletas',
        'nav.enrollments': 'Matrículas',
        'nav.competitions': 'Competições',
        'nav.training': 'Treinamentos',
        'nav.finance': 'Financeiro',
        'nav.subscription': 'Assinatura',
        'nav.settings': 'Configurações',
        'nav.logout': 'Sair',
        'nav.games': 'Jogos',

        // Auth
        'auth.login': 'Entrar',
        'auth.signup': 'Criar conta',
        'auth.forgotPassword': 'Esqueceu a senha?',
        'auth.email': 'E-mail',
        'auth.password': 'Senha',
        'auth.confirmPassword': 'Confirmar Senha',
        'auth.fullName': 'Nome Completo',
        'auth.language': 'Idioma',
        'auth.rememberMe': 'Lembrar de mim',
        'auth.noAccount': 'Não tem uma conta?',
        'auth.hasAccount': 'Já tem uma conta?',
        'auth.welcomeBack': 'Bem-vindo de volta',
        'auth.createAccount': 'Criar conta',
        'auth.enterCredentials': 'Entre com suas credenciais para acessar',
        'auth.fillData': 'Preencha os dados para começar',
        'auth.sendRecoveryLink': 'Enviar link de recuperação',
        'auth.backToLogin': 'Voltar ao login',
        'auth.recoverPassword': 'Recuperar senha',
        'auth.recoverPasswordDesc': 'Digite seu e-mail e enviaremos um link para redefinir sua senha.',
        'auth.emailSent': 'E-mail enviado!',
        'auth.accountCreated': 'Conta criada!',
        'auth.checkEmail': 'Verifique sua caixa de entrada para ativar sua conta.',
        'auth.goToLogin': 'Ir para o Login',

        // Common
        'common.loading': 'Carregando...',
        'common.save': 'Salvar',
        'common.cancel': 'Cancelar',
        'common.search': 'Buscar...',
        'common.filters': 'Filtros',
        'common.actions': 'Ações',
        'common.status': 'Status',
        'common.active': 'Ativo',
        'common.inactive': 'Inativo',
        'common.edit': 'Editar',
        'common.delete': 'Excluir',
        'common.create': 'Criar',
        'common.new': 'Novo',
        'common.all': 'Todos',
        'common.none': 'Nenhum',
        'common.yes': 'Sim',
        'common.no': 'Não',
        'common.back': 'Voltar',
        'common.next': 'Próximo',
        'common.previous': 'Anterior',
        'common.close': 'Fechar',
        'common.confirm': 'Confirmar',
        'common.clearFilters': 'Limpar filtros',
        'common.noResults': 'Nenhum resultado encontrado',
        'common.error': 'Erro',
        'common.success': 'Sucesso',
        'common.tryAgain': 'Tentar novamente',
        'common.comingSoon': 'Em breve',
        'common.registered': 'cadastrados',
        'common.ofTotal': 'da base total',
        'common.seeAll': 'Ver todos',
        'common.details': 'Detalhes',
        'common.viewDetails': 'Ver Detalhes',
        'common.noEmail': 'Sem e-mail',
        'common.noPosition': 'Sem posição',
        'common.noCategory': 'Sem categoria',
        'common.noName': 'Sem nome',
        'common.noDate': 'Sem data',
        'common.invalidDate': 'Data inválida',
        'common.dateNotDefined': 'Sem data definida',
        'common.locationTBD': 'Local a definir',
        'common.general': 'Geral',

        // Monthly Fees
        'monthlyFees.title': 'Mensalidades',
        'monthlyFees.overdue': 'em atraso',
        'monthlyFees.pending': 'pendentes',
        'monthlyFees.paid': 'pagas',

        // Dashboard
        'dashboard.title': 'Dashboard',
        'dashboard.totalAthletes': 'Total de Atletas',
        'dashboard.activeEnrollments': 'Matrículas Ativas',
        'dashboard.pendingFees': 'Mensalidades Pendentes',
        'dashboard.nextTraining': 'Próximo Treino',
        'dashboard.financialFlow': 'Fluxo Financeiro',
        'dashboard.revenueVsExpenses': 'Comparativo: Receita vs Despesas',
        'dashboard.weekly': 'Semanal',
        'dashboard.monthly': 'Mensal',
        'dashboard.upcomingGames': 'Próximos Jogos',
        'dashboard.noGamesScheduled': 'Nenhum jogo agendado',
        'dashboard.errorLoading': 'Erro ao carregar dados do dashboard',

        // Athletes
        'athletes.title': 'Atletas',
        'athletes.searchPlaceholder': 'Pesquisar atleta por nome ou categoria...',
        'athletes.registerAthlete': 'Cadastrar Atleta',
        'athletes.newAthlete': 'Novo Atleta',
        'athletes.deleteAthlete': 'Excluir Atleta',
        'athletes.deleteConfirm': 'Tem certeza que deseja excluir o atleta',
        'athletes.deleteWarning': 'Todos os dados relacionados (rouparia, fisiologia, histórico) também serão removidos.',
        'athletes.noAthletes': 'Nenhum atleta cadastrado',
        'athletes.noAthletesFiltered': 'Nenhum atleta encontrado com os filtros aplicados',
        'athletes.errorLoading': 'Erro ao carregar atletas',
        'athletes.errorDeleting': 'Erro ao excluir atleta',
        'athletes.athlete': 'Atleta',
        'athletes.athletes': 'atletas',
        'athletes.cpf': 'CPF',
        'athletes.category': 'Categoria',
        'athletes.position': 'Posição',
        'athletes.allCategories': 'Todas as categorias',
        'athletes.allPositions': 'Todas as posições',
        'athletes.allStatuses': 'Todos os status',
        'athletes.activeFilters': 'Filtros ativos',
        'athletes.status.active': 'Ativo',
        'athletes.status.inactive': 'Inativo',
        'athletes.status.injured': 'Lesionado',
        'athletes.status.suspended': 'Suspenso',

        // Training
        'training.title': 'Cronograma de Treinos',
        'training.scheduleTraining': 'Agendar Treino',
        'training.scheduleFirst': 'Agendar Primeiro Treino',
        'training.noTrainings': 'Nenhum treino agendado',
        'training.startScheduling': 'Comece agendando o primeiro treino do seu time.',
        'training.deleteTraining': 'Excluir Treino',
        'training.deleteConfirm': 'Tem certeza que deseja excluir este treino? Esta ação não pode ser desfeita.',
        'training.training': 'Treino',
        'training.trainings': 'treinos',
        'training.list': 'Lista',
        'training.calendar': 'Calendário',
        'training.category': 'Categoria',
        'training.status': 'Status',
        'training.intensity': 'Intensidade',
        'training.from': 'De',
        'training.to': 'Até',
        'training.allCategories': 'Todas',
        'training.allStatuses': 'Todos',
        'training.allIntensities': 'Todas',
        'training.more': 'mais',
        'training.status.scheduled': 'Agendado',
        'training.status.inProgress': 'Em Andamento',
        'training.status.completed': 'Concluído',
        'training.status.cancelled': 'Cancelado',
        'training.weekdays.sun': 'Dom',
        'training.weekdays.mon': 'Seg',
        'training.weekdays.tue': 'Ter',
        'training.weekdays.wed': 'Qua',
        'training.weekdays.thu': 'Qui',
        'training.weekdays.fri': 'Sex',
        'training.weekdays.sat': 'Sáb',

        // Competitions
        'competitions.title': 'Competições',
        'competitions.searchPlaceholder': 'Buscar competições...',
        'competitions.newCompetition': 'Nova Competição',
        'competitions.deleteCompetition': 'Excluir Competição',
        'competitions.deleteConfirm': 'Tem certeza que deseja excluir a competição',
        'competitions.deleteWarning': 'Todos os jogos relacionados também serão removidos.',
        'competitions.noCompetitions': 'Nenhuma competição cadastrada',
        'competitions.noCompetitionsFiltered': 'Nenhuma competição encontrada',
        'competitions.clickToStart': 'Clique em "Nova Competição" para começar',
        'competitions.competition': 'competição',
        'competitions.competitions': 'competições',
        'competitions.season': 'Temporada',
        'competitions.errorLoading': 'Erro ao carregar competições',
        'competitions.errorDeleting': 'Erro ao excluir competição',
        'competitions.status.upcoming': 'Próxima',
        'competitions.status.ongoing': 'Em Andamento',
        'competitions.status.finished': 'Finalizada',
        'competitions.status.cancelled': 'Cancelada',
        'competitions.type.league': 'Liga Regional',
        'competitions.type.cup': 'Copa',
        'competitions.type.tournament': 'Torneio',
        'competitions.type.friendly': 'Amistoso',
        'competitions.type.championship': 'Campeonato',
        'competitions.dateStart': 'Início',
        'competitions.dateEnd': 'Fim',

        // Games
        'games.title': 'Jogos',
        'games.newGame': 'Novo Jogo',
        'games.searchPlaceholder': 'Buscar jogos...',
        'games.game': 'Jogo',
        'games.homeTeam': 'Time da Casa',
        'games.awayTeam': 'Time Visitante',
        'games.vs': 'vs',
        'games.venue': 'Local',
        'games.date': 'Data',
        'games.time': 'Horário',
        'games.noGames': 'Nenhum jogo cadastrado',

        // Enrollments
        'enrollments.title': 'Matrículas',
        'enrollments.searchPlaceholder': 'Buscar por atleta...',
        'enrollments.newEnrollment': 'Nova Matrícula',
        'enrollments.deleteEnrollment': 'Excluir Matrícula',
        'enrollments.deleteConfirm': 'Tem certeza que deseja excluir a matrícula de',
        'enrollments.noEnrollments': 'Nenhuma matrícula cadastrada',
        'enrollments.noEnrollmentsFiltered': 'Nenhuma matrícula encontrada com os filtros aplicados',
        'enrollments.enrollment': 'matrícula',
        'enrollments.enrollments': 'matrículas',
        'enrollments.athlete': 'Atleta',
        'enrollments.plan': 'Plano',
        'enrollments.enrollmentDate': 'Matrícula',
        'enrollments.monthlyFee': 'Mensalidade',
        'enrollments.allStatuses': 'Todos os status',
        'enrollments.allPlans': 'Todos os planos',
        'enrollments.active': 'Ativas',
        'enrollments.pending': 'Pendentes',
        'enrollments.inactive': 'Inativas',
        'enrollments.errorLoading': 'Erro ao carregar matrículas',
        'enrollments.errorDeleting': 'Erro ao excluir matrícula',
        'enrollments.status.active': 'Ativa',
        'enrollments.status.pending': 'Pendente',
        'enrollments.status.cancelled': 'Cancelada',
        'enrollments.status.expired': 'Expirada',

        // Finance
        'finance.title': 'Financeiro',
        'finance.monthlyFees': 'Mensalidades',
        'finance.overview': 'Visão Geral',
        'finance.revenue': 'Receita',
        'finance.expenses': 'Despesas',
        'finance.balance': 'Saldo',

        // Subscription
        'subscription.title': 'Assinatura',
        'subscription.currentPlan': 'Plano Atual',
        'subscription.upgrade': 'Fazer Upgrade',
        'subscription.manage': 'Gerenciar Assinatura',

        // Languages
        'language.pt-BR': 'Português (Brasil)',
        'language.en-US': 'English (US)',
        'language.es-ES': 'Español',

        // Page Titles
        'pages.dashboard': 'Dashboard',
        'pages.athletes': 'Gestão de Atletas',
        'pages.enrollments': 'Gestão de Matrículas',
        'pages.competitions': 'Competições e Ligas',
        'pages.games': 'Jogos',
        'pages.training': 'Cronograma de Treinos',
        'pages.finance': 'Fluxo de Caixa',
        'pages.monthlyFees': 'Mensalidades e Cobranças',
        'pages.subscription': 'Minha Assinatura',
        'pages.plans': 'Planos de Assinatura',
        'pages.settings': 'Configurações do Clube',
    },
    'en-US': {
        // Navigation
        'nav.dashboard': 'Dashboard',
        'nav.athletes': 'Athletes',
        'nav.enrollments': 'Enrollments',
        'nav.competitions': 'Competitions',
        'nav.training': 'Training',
        'nav.finance': 'Finance',
        'nav.subscription': 'Subscription',
        'nav.settings': 'Settings',
        'nav.logout': 'Logout',
        'nav.games': 'Games',

        // Auth
        'auth.login': 'Login',
        'auth.signup': 'Sign up',
        'auth.forgotPassword': 'Forgot password?',
        'auth.email': 'Email',
        'auth.password': 'Password',
        'auth.confirmPassword': 'Confirm Password',
        'auth.fullName': 'Full Name',
        'auth.language': 'Language',
        'auth.rememberMe': 'Remember me',
        'auth.noAccount': "Don't have an account?",
        'auth.hasAccount': 'Already have an account?',
        'auth.welcomeBack': 'Welcome back',
        'auth.createAccount': 'Create account',
        'auth.enterCredentials': 'Enter your credentials to access',
        'auth.fillData': 'Fill in the data to get started',
        'auth.sendRecoveryLink': 'Send recovery link',
        'auth.backToLogin': 'Back to login',
        'auth.recoverPassword': 'Recover password',
        'auth.recoverPasswordDesc': 'Enter your email and we will send you a link to reset your password.',
        'auth.emailSent': 'Email sent!',
        'auth.accountCreated': 'Account created!',
        'auth.checkEmail': 'Check your inbox to activate your account.',
        'auth.goToLogin': 'Go to Login',

        // Common
        'common.loading': 'Loading...',
        'common.save': 'Save',
        'common.cancel': 'Cancel',
        'common.search': 'Search...',
        'common.filters': 'Filters',
        'common.actions': 'Actions',
        'common.status': 'Status',
        'common.active': 'Active',
        'common.inactive': 'Inactive',
        'common.edit': 'Edit',
        'common.delete': 'Delete',
        'common.create': 'Create',
        'common.new': 'New',
        'common.all': 'All',
        'common.none': 'None',
        'common.yes': 'Yes',
        'common.no': 'No',
        'common.back': 'Back',
        'common.next': 'Next',
        'common.previous': 'Previous',
        'common.close': 'Close',
        'common.confirm': 'Confirm',
        'common.clearFilters': 'Clear filters',
        'common.noResults': 'No results found',
        'common.error': 'Error',
        'common.success': 'Success',
        'common.tryAgain': 'Try again',
        'common.comingSoon': 'Coming soon',
        'common.registered': 'registered',
        'common.ofTotal': 'of total base',
        'common.seeAll': 'See all',
        'common.details': 'Details',
        'common.viewDetails': 'View Details',
        'common.noEmail': 'No email',
        'common.noPosition': 'No position',
        'common.noCategory': 'No category',
        'common.noName': 'No name',
        'common.noDate': 'No date',
        'common.invalidDate': 'Invalid date',
        'common.dateNotDefined': 'Date not defined',
        'common.locationTBD': 'Location TBD',
        'common.general': 'General',

        // Monthly Fees
        'monthlyFees.title': 'Monthly Fees',
        'monthlyFees.overdue': 'overdue',
        'monthlyFees.pending': 'pending',
        'monthlyFees.paid': 'paid',

        // Dashboard
        'dashboard.title': 'Dashboard',
        'dashboard.totalAthletes': 'Total Athletes',
        'dashboard.activeEnrollments': 'Active Enrollments',
        'dashboard.pendingFees': 'Pending Fees',
        'dashboard.nextTraining': 'Next Training',
        'dashboard.financialFlow': 'Financial Flow',
        'dashboard.revenueVsExpenses': 'Comparison: Revenue vs Expenses',
        'dashboard.weekly': 'Weekly',
        'dashboard.monthly': 'Monthly',
        'dashboard.upcomingGames': 'Upcoming Games',
        'dashboard.noGamesScheduled': 'No games scheduled',
        'dashboard.errorLoading': 'Error loading dashboard data',

        // Athletes
        'athletes.title': 'Athletes',
        'athletes.searchPlaceholder': 'Search athlete by name or category...',
        'athletes.registerAthlete': 'Register Athlete',
        'athletes.newAthlete': 'New Athlete',
        'athletes.deleteAthlete': 'Delete Athlete',
        'athletes.deleteConfirm': 'Are you sure you want to delete the athlete',
        'athletes.deleteWarning': 'All related data (gear, physiology, history) will also be removed.',
        'athletes.noAthletes': 'No athletes registered',
        'athletes.noAthletesFiltered': 'No athletes found with applied filters',
        'athletes.errorLoading': 'Error loading athletes',
        'athletes.errorDeleting': 'Error deleting athlete',
        'athletes.athlete': 'Athlete',
        'athletes.athletes': 'athletes',
        'athletes.cpf': 'ID Number',
        'athletes.category': 'Category',
        'athletes.position': 'Position',
        'athletes.allCategories': 'All categories',
        'athletes.allPositions': 'All positions',
        'athletes.allStatuses': 'All statuses',
        'athletes.activeFilters': 'Active filters',
        'athletes.status.active': 'Active',
        'athletes.status.inactive': 'Inactive',
        'athletes.status.injured': 'Injured',
        'athletes.status.suspended': 'Suspended',

        // Training
        'training.title': 'Training Schedule',
        'training.scheduleTraining': 'Schedule Training',
        'training.scheduleFirst': 'Schedule First Training',
        'training.noTrainings': 'No training scheduled',
        'training.startScheduling': 'Start by scheduling your team\'s first training.',
        'training.deleteTraining': 'Delete Training',
        'training.deleteConfirm': 'Are you sure you want to delete this training? This action cannot be undone.',
        'training.training': 'Training',
        'training.trainings': 'trainings',
        'training.list': 'List',
        'training.calendar': 'Calendar',
        'training.category': 'Category',
        'training.status': 'Status',
        'training.intensity': 'Intensity',
        'training.from': 'From',
        'training.to': 'To',
        'training.allCategories': 'All',
        'training.allStatuses': 'All',
        'training.allIntensities': 'All',
        'training.more': 'more',
        'training.status.scheduled': 'Scheduled',
        'training.status.inProgress': 'In Progress',
        'training.status.completed': 'Completed',
        'training.status.cancelled': 'Cancelled',
        'training.weekdays.sun': 'Sun',
        'training.weekdays.mon': 'Mon',
        'training.weekdays.tue': 'Tue',
        'training.weekdays.wed': 'Wed',
        'training.weekdays.thu': 'Thu',
        'training.weekdays.fri': 'Fri',
        'training.weekdays.sat': 'Sat',

        // Competitions
        'competitions.title': 'Competitions',
        'competitions.searchPlaceholder': 'Search competitions...',
        'competitions.newCompetition': 'New Competition',
        'competitions.deleteCompetition': 'Delete Competition',
        'competitions.deleteConfirm': 'Are you sure you want to delete the competition',
        'competitions.deleteWarning': 'All related games will also be removed.',
        'competitions.noCompetitions': 'No competitions registered',
        'competitions.noCompetitionsFiltered': 'No competitions found',
        'competitions.clickToStart': 'Click "New Competition" to start',
        'competitions.competition': 'competition',
        'competitions.competitions': 'competitions',
        'competitions.season': 'Season',
        'competitions.errorLoading': 'Error loading competitions',
        'competitions.errorDeleting': 'Error deleting competition',
        'competitions.status.upcoming': 'Upcoming',
        'competitions.status.ongoing': 'Ongoing',
        'competitions.status.finished': 'Finished',
        'competitions.status.cancelled': 'Cancelled',
        'competitions.type.league': 'Regional League',
        'competitions.type.cup': 'Cup',
        'competitions.type.tournament': 'Tournament',
        'competitions.type.friendly': 'Friendly',
        'competitions.type.championship': 'Championship',
        'competitions.dateStart': 'Start',
        'competitions.dateEnd': 'End',

        // Games
        'games.title': 'Games',
        'games.newGame': 'New Game',
        'games.searchPlaceholder': 'Search games...',
        'games.game': 'Game',
        'games.homeTeam': 'Home Team',
        'games.awayTeam': 'Away Team',
        'games.vs': 'vs',
        'games.venue': 'Venue',
        'games.date': 'Date',
        'games.time': 'Time',
        'games.noGames': 'No games registered',

        // Enrollments
        'enrollments.title': 'Enrollments',
        'enrollments.searchPlaceholder': 'Search by athlete...',
        'enrollments.newEnrollment': 'New Enrollment',
        'enrollments.deleteEnrollment': 'Delete Enrollment',
        'enrollments.deleteConfirm': 'Are you sure you want to delete the enrollment of',
        'enrollments.noEnrollments': 'No enrollments registered',
        'enrollments.noEnrollmentsFiltered': 'No enrollments found with applied filters',
        'enrollments.enrollment': 'enrollment',
        'enrollments.enrollments': 'enrollments',
        'enrollments.athlete': 'Athlete',
        'enrollments.plan': 'Plan',
        'enrollments.enrollmentDate': 'Enrollment',
        'enrollments.monthlyFee': 'Monthly Fee',
        'enrollments.allStatuses': 'All statuses',
        'enrollments.allPlans': 'All plans',
        'enrollments.active': 'Active',
        'enrollments.pending': 'Pending',
        'enrollments.inactive': 'Inactive',
        'enrollments.errorLoading': 'Error loading enrollments',
        'enrollments.errorDeleting': 'Error deleting enrollment',
        'enrollments.status.active': 'Active',
        'enrollments.status.pending': 'Pending',
        'enrollments.status.cancelled': 'Cancelled',
        'enrollments.status.expired': 'Expired',

        // Finance
        'finance.title': 'Finance',
        'finance.monthlyFees': 'Monthly Fees',
        'finance.overview': 'Overview',
        'finance.revenue': 'Revenue',
        'finance.expenses': 'Expenses',
        'finance.balance': 'Balance',

        // Subscription
        'subscription.title': 'Subscription',
        'subscription.currentPlan': 'Current Plan',
        'subscription.upgrade': 'Upgrade',
        'subscription.manage': 'Manage Subscription',

        // Languages
        'language.pt-BR': 'Portuguese (Brazil)',
        'language.en-US': 'English (US)',
        'language.es-ES': 'Spanish',

        // Page Titles
        'pages.dashboard': 'Dashboard',
        'pages.athletes': 'Athlete Management',
        'pages.enrollments': 'Enrollment Management',
        'pages.competitions': 'Competitions & Leagues',
        'pages.games': 'Games',
        'pages.training': 'Training Schedule',
        'pages.finance': 'Cash Flow',
        'pages.monthlyFees': 'Monthly Fees & Billing',
        'pages.subscription': 'My Subscription',
        'pages.plans': 'Subscription Plans',
        'pages.settings': 'Club Settings',
    },
    'es-ES': {
        // Navigation
        'nav.dashboard': 'Panel',
        'nav.athletes': 'Atletas',
        'nav.enrollments': 'Inscripciones',
        'nav.competitions': 'Competiciones',
        'nav.training': 'Entrenamientos',
        'nav.finance': 'Finanzas',
        'nav.subscription': 'Suscripción',
        'nav.settings': 'Configuración',
        'nav.logout': 'Salir',
        'nav.games': 'Partidos',

        // Auth
        'auth.login': 'Iniciar sesión',
        'auth.signup': 'Registrarse',
        'auth.forgotPassword': '¿Olvidaste tu contraseña?',
        'auth.email': 'Correo electrónico',
        'auth.password': 'Contraseña',
        'auth.confirmPassword': 'Confirmar Contraseña',
        'auth.fullName': 'Nombre Completo',
        'auth.language': 'Idioma',
        'auth.rememberMe': 'Recordarme',
        'auth.noAccount': '¿No tienes una cuenta?',
        'auth.hasAccount': '¿Ya tienes una cuenta?',
        'auth.welcomeBack': 'Bienvenido de nuevo',
        'auth.createAccount': 'Crear cuenta',
        'auth.enterCredentials': 'Ingresa tus credenciales para acceder',
        'auth.fillData': 'Completa los datos para comenzar',
        'auth.sendRecoveryLink': 'Enviar enlace de recuperación',
        'auth.backToLogin': 'Volver al inicio de sesión',
        'auth.recoverPassword': 'Recuperar contraseña',
        'auth.recoverPasswordDesc': 'Ingresa tu correo y te enviaremos un enlace para restablecer tu contraseña.',
        'auth.emailSent': '¡Correo enviado!',
        'auth.accountCreated': '¡Cuenta creada!',
        'auth.checkEmail': 'Revisa tu bandeja de entrada para activar tu cuenta.',
        'auth.goToLogin': 'Ir al inicio de sesión',

        // Common
        'common.loading': 'Cargando...',
        'common.save': 'Guardar',
        'common.cancel': 'Cancelar',
        'common.search': 'Buscar...',
        'common.filters': 'Filtros',
        'common.actions': 'Acciones',
        'common.status': 'Estado',
        'common.active': 'Activo',
        'common.inactive': 'Inactivo',
        'common.edit': 'Editar',
        'common.delete': 'Eliminar',
        'common.create': 'Crear',
        'common.new': 'Nuevo',
        'common.all': 'Todos',
        'common.none': 'Ninguno',
        'common.yes': 'Sí',
        'common.no': 'No',
        'common.back': 'Volver',
        'common.next': 'Siguiente',
        'common.previous': 'Anterior',
        'common.close': 'Cerrar',
        'common.confirm': 'Confirmar',
        'common.clearFilters': 'Limpiar filtros',
        'common.noResults': 'No se encontraron resultados',
        'common.error': 'Error',
        'common.success': 'Éxito',
        'common.tryAgain': 'Intentar de nuevo',
        'common.comingSoon': 'Próximamente',
        'common.registered': 'registrados',
        'common.ofTotal': 'de la base total',
        'common.seeAll': 'Ver todos',
        'common.details': 'Detalles',
        'common.viewDetails': 'Ver Detalles',
        'common.noEmail': 'Sin correo',
        'common.noPosition': 'Sin posición',
        'common.noCategory': 'Sin categoría',
        'common.noName': 'Sin nombre',
        'common.noDate': 'Sin fecha',
        'common.invalidDate': 'Fecha inválida',
        'common.dateNotDefined': 'Fecha no definida',
        'common.locationTBD': 'Lugar por definir',
        'common.general': 'General',

        // Monthly Fees
        'monthlyFees.title': 'Cuotas Mensuales',
        'monthlyFees.overdue': 'atrasadas',
        'monthlyFees.pending': 'pendientes',
        'monthlyFees.paid': 'pagadas',

        // Dashboard
        'dashboard.title': 'Panel',
        'dashboard.totalAthletes': 'Total de Atletas',
        'dashboard.activeEnrollments': 'Inscripciones Activas',
        'dashboard.pendingFees': 'Cuotas Pendientes',
        'dashboard.nextTraining': 'Próximo Entrenamiento',
        'dashboard.financialFlow': 'Flujo Financiero',
        'dashboard.revenueVsExpenses': 'Comparativo: Ingresos vs Gastos',
        'dashboard.weekly': 'Semanal',
        'dashboard.monthly': 'Mensual',
        'dashboard.upcomingGames': 'Próximos Partidos',
        'dashboard.noGamesScheduled': 'No hay partidos programados',
        'dashboard.errorLoading': 'Error al cargar datos del panel',

        // Athletes
        'athletes.title': 'Atletas',
        'athletes.searchPlaceholder': 'Buscar atleta por nombre o categoría...',
        'athletes.registerAthlete': 'Registrar Atleta',
        'athletes.newAthlete': 'Nuevo Atleta',
        'athletes.deleteAthlete': 'Eliminar Atleta',
        'athletes.deleteConfirm': '¿Estás seguro de que deseas eliminar al atleta',
        'athletes.deleteWarning': 'Todos los datos relacionados (equipamiento, fisiología, historial) también serán eliminados.',
        'athletes.noAthletes': 'No hay atletas registrados',
        'athletes.noAthletesFiltered': 'No se encontraron atletas con los filtros aplicados',
        'athletes.errorLoading': 'Error al cargar atletas',
        'athletes.errorDeleting': 'Error al eliminar atleta',
        'athletes.athlete': 'Atleta',
        'athletes.athletes': 'atletas',
        'athletes.cpf': 'Documento',
        'athletes.category': 'Categoría',
        'athletes.position': 'Posición',
        'athletes.allCategories': 'Todas las categorías',
        'athletes.allPositions': 'Todas las posiciones',
        'athletes.allStatuses': 'Todos los estados',
        'athletes.activeFilters': 'Filtros activos',
        'athletes.status.active': 'Activo',
        'athletes.status.inactive': 'Inactivo',
        'athletes.status.injured': 'Lesionado',
        'athletes.status.suspended': 'Suspendido',

        // Training
        'training.title': 'Cronograma de Entrenamientos',
        'training.scheduleTraining': 'Programar Entrenamiento',
        'training.scheduleFirst': 'Programar Primer Entrenamiento',
        'training.noTrainings': 'No hay entrenamientos programados',
        'training.startScheduling': 'Comienza programando el primer entrenamiento de tu equipo.',
        'training.deleteTraining': 'Eliminar Entrenamiento',
        'training.deleteConfirm': '¿Estás seguro de que deseas eliminar este entrenamiento? Esta acción no se puede deshacer.',
        'training.training': 'Entrenamiento',
        'training.trainings': 'entrenamientos',
        'training.list': 'Lista',
        'training.calendar': 'Calendario',
        'training.category': 'Categoría',
        'training.status': 'Estado',
        'training.intensity': 'Intensidad',
        'training.from': 'Desde',
        'training.to': 'Hasta',
        'training.allCategories': 'Todas',
        'training.allStatuses': 'Todos',
        'training.allIntensities': 'Todas',
        'training.more': 'más',
        'training.status.scheduled': 'Programado',
        'training.status.inProgress': 'En Progreso',
        'training.status.completed': 'Completado',
        'training.status.cancelled': 'Cancelado',
        'training.weekdays.sun': 'Dom',
        'training.weekdays.mon': 'Lun',
        'training.weekdays.tue': 'Mar',
        'training.weekdays.wed': 'Mié',
        'training.weekdays.thu': 'Jue',
        'training.weekdays.fri': 'Vie',
        'training.weekdays.sat': 'Sáb',

        // Competitions
        'competitions.title': 'Competiciones',
        'competitions.searchPlaceholder': 'Buscar competiciones...',
        'competitions.newCompetition': 'Nueva Competición',
        'competitions.deleteCompetition': 'Eliminar Competición',
        'competitions.deleteConfirm': '¿Estás seguro de que deseas eliminar la competición',
        'competitions.deleteWarning': 'Todos los partidos relacionados también serán eliminados.',
        'competitions.noCompetitions': 'No hay competiciones registradas',
        'competitions.noCompetitionsFiltered': 'No se encontraron competiciones',
        'competitions.clickToStart': 'Haz clic en "Nueva Competición" para comenzar',
        'competitions.competition': 'competición',
        'competitions.competitions': 'competiciones',
        'competitions.season': 'Temporada',
        'competitions.errorLoading': 'Error al cargar competiciones',
        'competitions.errorDeleting': 'Error al eliminar competición',
        'competitions.status.upcoming': 'Próxima',
        'competitions.status.ongoing': 'En Curso',
        'competitions.status.finished': 'Finalizada',
        'competitions.status.cancelled': 'Cancelada',
        'competitions.type.league': 'Liga Regional',
        'competitions.type.cup': 'Copa',
        'competitions.type.tournament': 'Torneo',
        'competitions.type.friendly': 'Amistoso',
        'competitions.type.championship': 'Campeonato',
        'competitions.dateStart': 'Inicio',
        'competitions.dateEnd': 'Fin',

        // Games
        'games.title': 'Partidos',
        'games.newGame': 'Nuevo Partido',
        'games.searchPlaceholder': 'Buscar partidos...',
        'games.game': 'Partido',
        'games.homeTeam': 'Equipo Local',
        'games.awayTeam': 'Equipo Visitante',
        'games.vs': 'vs',
        'games.venue': 'Lugar',
        'games.date': 'Fecha',
        'games.time': 'Hora',
        'games.noGames': 'No hay partidos registrados',

        // Enrollments
        'enrollments.title': 'Inscripciones',
        'enrollments.searchPlaceholder': 'Buscar por atleta...',
        'enrollments.newEnrollment': 'Nueva Inscripción',
        'enrollments.deleteEnrollment': 'Eliminar Inscripción',
        'enrollments.deleteConfirm': '¿Estás seguro de que deseas eliminar la inscripción de',
        'enrollments.noEnrollments': 'No hay inscripciones registradas',
        'enrollments.noEnrollmentsFiltered': 'No se encontraron inscripciones con los filtros aplicados',
        'enrollments.enrollment': 'inscripción',
        'enrollments.enrollments': 'inscripciones',
        'enrollments.athlete': 'Atleta',
        'enrollments.plan': 'Plan',
        'enrollments.enrollmentDate': 'Inscripción',
        'enrollments.monthlyFee': 'Cuota Mensual',
        'enrollments.allStatuses': 'Todos los estados',
        'enrollments.allPlans': 'Todos los planes',
        'enrollments.active': 'Activas',
        'enrollments.pending': 'Pendientes',
        'enrollments.inactive': 'Inactivas',
        'enrollments.errorLoading': 'Error al cargar inscripciones',
        'enrollments.errorDeleting': 'Error al eliminar inscripción',
        'enrollments.status.active': 'Activa',
        'enrollments.status.pending': 'Pendiente',
        'enrollments.status.cancelled': 'Cancelada',
        'enrollments.status.expired': 'Expirada',

        // Finance
        'finance.title': 'Finanzas',
        'finance.monthlyFees': 'Cuotas Mensuales',
        'finance.overview': 'Resumen',
        'finance.revenue': 'Ingresos',
        'finance.expenses': 'Gastos',
        'finance.balance': 'Saldo',

        // Subscription
        'subscription.title': 'Suscripción',
        'subscription.currentPlan': 'Plan Actual',
        'subscription.upgrade': 'Mejorar Plan',
        'subscription.manage': 'Gestionar Suscripción',

        // Languages
        'language.pt-BR': 'Portugués (Brasil)',
        'language.en-US': 'Inglés (EE.UU.)',
        'language.es-ES': 'Español',

        // Page Titles
        'pages.dashboard': 'Panel de Control',
        'pages.athletes': 'Gestión de Atletas',
        'pages.enrollments': 'Gestión de Inscripciones',
        'pages.competitions': 'Competiciones y Ligas',
        'pages.games': 'Partidos',
        'pages.training': 'Calendario de Entrenamientos',
        'pages.finance': 'Flujo de Caja',
        'pages.monthlyFees': 'Mensualidades y Cobros',
        'pages.subscription': 'Mi Suscripción',
        'pages.plans': 'Planes de Suscripción',
        'pages.settings': 'Configuración del Club',
    },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [language, setLanguageState] = useState<Language>('pt-BR');
    const { user } = useAuth();

    // Load language from user profile
    useEffect(() => {
        const loadLanguage = async () => {
            if (user) {
                const { data } = await supabase
                    .from('profiles')
                    .select('language')
                    .eq('id', user.id)
                    .single();

                if (data?.language) {
                    setLanguageState(data.language as Language);
                }
            } else {
                // Try to load from localStorage for non-authenticated users
                const savedLang = localStorage.getItem('language') as Language;
                if (savedLang && translations[savedLang]) {
                    setLanguageState(savedLang);
                }
            }
        };

        loadLanguage();
    }, [user]);

    const setLanguage = async (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem('language', lang);

        // Update in database if user is authenticated
        if (user) {
            await supabase
                .from('profiles')
                .update({ language: lang, updated_at: new Date().toISOString() })
                .eq('id', user.id);
        }
    };

    const t = (key: string): string => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const AVAILABLE_LANGUAGES: { value: Language; label: string }[] = [
    { value: 'pt-BR', label: 'Português (Brasil)' },
    { value: 'en-US', label: 'English (US)' },
    { value: 'es-ES', label: 'Español' },
];
