const fs = require('fs');
const path = require('path');

const contextPath = path.resolve(__dirname, '../contexts/LanguageContext.tsx');
let content = fs.readFileSync(contextPath, 'utf8');

const keysData = {
    "pt-BR": {
        "enrollmentForm.title": "Matrículas",
        "enrollmentForm.newTitle": "Nova Matrícula",
        "enrollmentForm.editTitle": "Editar Matrícula",
        "enrollmentForm.newSubtitle": "Preencha os dados do atleta e da matrícula",
        "enrollmentForm.editSubtitle": "Atualize os dados da matrícula",
        "enrollmentForm.section.athlete": "Dados do Atleta",
        "enrollmentForm.section.enrollment": "Dados da Matrícula",
        "enrollmentForm.section.plan": "Plano e Pagamento",
        "enrollmentForm.section.contract": "Contrato",
        "enrollmentForm.section.guardian": "Responsável (para menores de idade)",
        "enrollmentForm.field.guardianName": "Nome do Responsável",
        "enrollmentForm.field.guardianPhone": "Telefone do Responsável",
        "enrollmentForm.field.enrollmentDate": "Data da Matrícula",
        "enrollmentForm.field.startDate": "Data de Início",
        "enrollmentForm.field.status": "Status",
        "enrollmentForm.field.planType": "Tipo de Plano",
        "enrollmentForm.field.monthlyFee": "Mensalidade",
        "enrollmentForm.field.paymentDay": "Dia de Vencimento",
        "enrollmentForm.field.paymentMethod": "Forma de Pagamento",
        "enrollmentForm.field.contractSigned": "Contrato assinado",
        "enrollmentForm.field.contractDate": "Data de assinatura",
        "enrollmentForm.status.pending": "Pendente",
        "enrollmentForm.status.active": "Ativa",
        "enrollmentForm.status.cancelled": "Cancelada",
        "enrollmentForm.status.expired": "Expirada",
        "enrollmentForm.error.loading": "Erro ao carregar matrícula",
        "enrollmentForm.error.saving": "Erro ao salvar matrícula",
        "competitionForm.newTitle": "Nova Competição",
        "competitionForm.editTitle": "Editar Competição",
        "competitionForm.newSubtitle": "Preencha os dados e adicione os jogos",
        "competitionForm.editSubtitle": "Atualize os dados da competição",
        "competitionForm.section.info": "Informações da Competição",
        "competitionForm.section.results": "Resultado Final",
        "competitionForm.section.games": "Jogos",
        "competitionForm.field.name": "Nome",
        "competitionForm.field.type": "Tipo",
        "competitionForm.field.category": "Categoria",
        "competitionForm.field.season": "Temporada",
        "competitionForm.field.startDate": "Início",
        "competitionForm.field.endDate": "Fim",
        "competitionForm.field.status": "Status",
        "competitionForm.field.organizer": "Organizador",
        "competitionForm.field.description": "Descrição",
        "competitionForm.stats.finalPosition": "Colocação Final",
        "competitionForm.stats.totalTeams": "Total de Equipes",
        "competitionForm.stats.title": "Estatísticas",
        "competitionForm.stats.wins": "Vitórias",
        "competitionForm.stats.draws": "Empates",
        "competitionForm.stats.losses": "Derrotas",
        "competitionForm.stats.goalsFor": "Gols Pró",
        "competitionForm.stats.goalsAgainst": "Gols Contra",
        "competitionForm.game.add": "Adicionar Jogo",
        "competitionForm.game.empty": "Nenhum jogo cadastrado",
        "competitionForm.game.emptyDesc": "Clique em \"Adicionar Jogo\" para começar",
        "competitionForm.game.round": "Rodada",
        "competitionForm.game.venue": "Local",
        "competitionForm.game.score": "Placar",
        "competitionForm.error.loading": "Erro ao carregar competição",
        "competitionForm.error.saving": "Erro ao salvar competição",
        "competitionForm.error.nameRequired": "O nome da competição é obrigatório"
    },
    "en-US": {
        "enrollmentForm.title": "Enrollments",
        "enrollmentForm.newTitle": "New Enrollment",
        "enrollmentForm.editTitle": "Edit Enrollment",
        "enrollmentForm.newSubtitle": "Fill in the athlete and enrollment details",
        "enrollmentForm.editSubtitle": "Update enrollment details",
        "enrollmentForm.section.athlete": "Athlete Data",
        "enrollmentForm.section.enrollment": "Enrollment Data",
        "enrollmentForm.section.plan": "Plan and Payment",
        "enrollmentForm.section.contract": "Contract",
        "enrollmentForm.section.guardian": "Guardian (for minors)",
        "enrollmentForm.field.guardianName": "Guardian Name",
        "enrollmentForm.field.guardianPhone": "Guardian Phone",
        "enrollmentForm.field.enrollmentDate": "Enrollment Date",
        "enrollmentForm.field.startDate": "Start Date",
        "enrollmentForm.field.status": "Status",
        "enrollmentForm.field.planType": "Plan Type",
        "enrollmentForm.field.monthlyFee": "Monthly Fee",
        "enrollmentForm.field.paymentDay": "Payment Day",
        "enrollmentForm.field.paymentMethod": "Payment Method",
        "enrollmentForm.field.contractSigned": "Contract signed",
        "enrollmentForm.field.contractDate": "Signature date",
        "enrollmentForm.status.pending": "Pending",
        "enrollmentForm.status.active": "Active",
        "enrollmentForm.status.cancelled": "Cancelled",
        "enrollmentForm.status.expired": "Expired",
        "enrollmentForm.error.loading": "Error loading enrollment",
        "enrollmentForm.error.saving": "Error saving enrollment",
        "competitionForm.newTitle": "New Competition",
        "competitionForm.editTitle": "Edit Competition",
        "competitionForm.newSubtitle": "Fill in details and add games",
        "competitionForm.editSubtitle": "Update competition details",
        "competitionForm.section.info": "Competition Information",
        "competitionForm.section.results": "Final Results",
        "competitionForm.section.games": "Games",
        "competitionForm.field.name": "Name",
        "competitionForm.field.type": "Type",
        "competitionForm.field.category": "Category",
        "competitionForm.field.season": "Season",
        "competitionForm.field.startDate": "Start Date",
        "competitionForm.field.endDate": "End Date",
        "competitionForm.field.status": "Status",
        "competitionForm.field.organizer": "Organizer",
        "competitionForm.field.description": "Description",
        "competitionForm.stats.finalPosition": "Final Position",
        "competitionForm.stats.totalTeams": "Total Teams",
        "competitionForm.stats.title": "Statistics",
        "competitionForm.stats.wins": "Wins",
        "competitionForm.stats.draws": "Draws",
        "competitionForm.stats.losses": "Losses",
        "competitionForm.stats.goalsFor": "Goals For",
        "competitionForm.stats.goalsAgainst": "Goals Against",
        "competitionForm.game.add": "Add Game",
        "competitionForm.game.empty": "No games registered",
        "competitionForm.game.emptyDesc": "Click \"Add Game\" to start",
        "competitionForm.game.round": "Round",
        "competitionForm.game.venue": "Venue",
        "competitionForm.game.score": "Score",
        "competitionForm.error.loading": "Error loading competition",
        "competitionForm.error.saving": "Error saving competition",
        "competitionForm.error.nameRequired": "Competition name is required"
    },
    "es-ES": {
        "enrollmentForm.title": "Matrículas",
        "enrollmentForm.newTitle": "Nueva Matrícula",
        "enrollmentForm.editTitle": "Editar Matrícula",
        "enrollmentForm.newSubtitle": "Llene los datos del atleta y de la matrícula",
        "enrollmentForm.editSubtitle": "Actualice los datos de la matrícula",
        "enrollmentForm.section.athlete": "Datos del Atleta",
        "enrollmentForm.section.enrollment": "Datos de la Matrícula",
        "enrollmentForm.section.plan": "Plan y Pago",
        "enrollmentForm.section.contract": "Contrato",
        "enrollmentForm.section.guardian": "Responsable (para menores de edad)",
        "enrollmentForm.field.guardianName": "Nombre del Responsable",
        "enrollmentForm.field.guardianPhone": "Teléfono del Responsable",
        "enrollmentForm.field.enrollmentDate": "Fecha de Matrícula",
        "enrollmentForm.field.startDate": "Fecha de Inicio",
        "enrollmentForm.field.status": "Estado",
        "enrollmentForm.field.planType": "Tipo de Plan",
        "enrollmentForm.field.monthlyFee": "Mensualidad",
        "enrollmentForm.field.paymentDay": "Día de Pago",
        "enrollmentForm.field.paymentMethod": "Método de Pago",
        "enrollmentForm.field.contractSigned": "Contrato firmado",
        "enrollmentForm.field.contractDate": "Fecha de firma",
        "enrollmentForm.status.pending": "Pendiente",
        "enrollmentForm.status.active": "Activa",
        "enrollmentForm.status.cancelled": "Cancelada",
        "enrollmentForm.status.expired": "Expirada",
        "enrollmentForm.error.loading": "Error al cargar la matrícula",
        "enrollmentForm.error.saving": "Error al guardar la matrícula",
        "competitionForm.newTitle": "Nueva Competición",
        "competitionForm.editTitle": "Editar Competición",
        "competitionForm.newSubtitle": "Llene los datos y añada los juegos",
        "competitionForm.editSubtitle": "Actualice los datos de la competición",
        "competitionForm.section.info": "Información de la Competición",
        "competitionForm.section.results": "Resultado Final",
        "competitionForm.section.games": "Juegos",
        "competitionForm.field.name": "Nombre",
        "competitionForm.field.type": "Tipo",
        "competitionForm.field.category": "Categoría",
        "competitionForm.field.season": "Temporada",
        "competitionForm.field.startDate": "Inicio",
        "competitionForm.field.endDate": "Fin",
        "competitionForm.field.status": "Estado",
        "competitionForm.field.organizer": "Organizador",
        "competitionForm.field.description": "Descripción",
        "competitionForm.stats.finalPosition": "Posición Final",
        "competitionForm.stats.totalTeams": "Total de Equipos",
        "competitionForm.stats.title": "Estadísticas",
        "competitionForm.stats.wins": "Victorias",
        "competitionForm.stats.draws": "Empates",
        "competitionForm.stats.losses": "Derrotas",
        "competitionForm.stats.goalsFor": "Goles a Favor",
        "competitionForm.stats.goalsAgainst": "Goles en Contra",
        "competitionForm.game.add": "Añadir Juego",
        "competitionForm.game.empty": "Ningún juego registrado",
        "competitionForm.game.emptyDesc": "Haga clic en \"Añadir Juego\" para comenzar",
        "competitionForm.game.round": "Ronda",
        "competitionForm.game.venue": "Lugar",
        "competitionForm.game.score": "Marcador",
        "competitionForm.error.loading": "Error al cargar la competición",
        "competitionForm.error.saving": "Error al guardar la competición",
        "competitionForm.error.nameRequired": "El nombre de la competición es obligatorio"
    },
    "fr-FR": {
        "enrollmentForm.title": "Inscriptions",
        "enrollmentForm.newTitle": "Nouvelle Inscription",
        "enrollmentForm.editTitle": "Modifier Inscription",
        "enrollmentForm.newSubtitle": "Saisissez les données de l'athlète et de l'inscription",
        "enrollmentForm.editSubtitle": "Mettre à jour l'inscription",
        "enrollmentForm.section.athlete": "Données de l'athlète",
        "enrollmentForm.section.enrollment": "Données d'inscription",
        "enrollmentForm.section.plan": "Abonnement et Paiement",
        "enrollmentForm.section.contract": "Contrat",
        "enrollmentForm.section.guardian": "Responsable (pour mineurs)",
        "enrollmentForm.field.guardianName": "Nom du Responsable",
        "enrollmentForm.field.guardianPhone": "Téléphone du Responsable",
        "enrollmentForm.field.enrollmentDate": "Date d'inscription",
        "enrollmentForm.field.startDate": "Date de Début",
        "enrollmentForm.field.status": "Statut",
        "enrollmentForm.field.planType": "Type de Plan",
        "enrollmentForm.field.monthlyFee": "Mensualité",
        "enrollmentForm.field.paymentDay": "Jour de Paiement",
        "enrollmentForm.field.paymentMethod": "Mode de Paiement",
        "enrollmentForm.field.contractSigned": "Contrat signé",
        "enrollmentForm.field.contractDate": "Date de signature",
        "enrollmentForm.status.pending": "En attente",
        "enrollmentForm.status.active": "Active",
        "enrollmentForm.status.cancelled": "Annulée",
        "enrollmentForm.status.expired": "Expirée",
        "enrollmentForm.error.loading": "Erreur de chargement",
        "enrollmentForm.error.saving": "Erreur de sauvegarde",
        "competitionForm.newTitle": "Nouvelle Compétition",
        "competitionForm.editTitle": "Modifier Compétition",
        "competitionForm.newSubtitle": "Remplissez les détails et ajoutez des matchs",
        "competitionForm.editSubtitle": "Mettre à jour la compétition",
        "competitionForm.section.info": "Informations sur la compétition",
        "competitionForm.section.results": "Résultat Final",
        "competitionForm.section.games": "Matchs",
        "competitionForm.field.name": "Nom",
        "competitionForm.field.type": "Type",
        "competitionForm.field.category": "Catégorie",
        "competitionForm.field.season": "Saison",
        "competitionForm.field.startDate": "Début",
        "competitionForm.field.endDate": "Fin",
        "competitionForm.field.status": "Statut",
        "competitionForm.field.organizer": "Organisateur",
        "competitionForm.field.description": "Description",
        "competitionForm.stats.finalPosition": "Position finale",
        "competitionForm.stats.totalTeams": "Nombre d'équipes",
        "competitionForm.stats.title": "Statistiques",
        "competitionForm.stats.wins": "Victoires",
        "competitionForm.stats.draws": "Nuls",
        "competitionForm.stats.losses": "Défaites",
        "competitionForm.stats.goalsFor": "Buts Pour",
        "competitionForm.stats.goalsAgainst": "Buts Contre",
        "competitionForm.game.add": "Ajouter un match",
        "competitionForm.game.empty": "Aucun match",
        "competitionForm.game.emptyDesc": "Cliquez pour ajouter un match",
        "competitionForm.game.round": "Tour/Journée",
        "competitionForm.game.venue": "Stade/Lieu",
        "competitionForm.game.score": "Score",
        "competitionForm.error.loading": "Erreur de chargement",
        "competitionForm.error.saving": "Erreur de sauvegarde",
        "competitionForm.error.nameRequired": "Le nom est obligatoire"
    },
    "pt-PT": {
        "enrollmentForm.title": "Matrículas",
        "enrollmentForm.newTitle": "Nova Matrícula",
        "enrollmentForm.editTitle": "Editar Matrícula",
        "enrollmentForm.newSubtitle": "Preencha os dados do atleta e da matrícula",
        "enrollmentForm.editSubtitle": "Atualize os dados da matrícula",
        "enrollmentForm.section.athlete": "Dados do Atleta",
        "enrollmentForm.section.enrollment": "Dados da Matrícula",
        "enrollmentForm.section.plan": "Plano e Pagamento",
        "enrollmentForm.section.contract": "Contrato",
        "enrollmentForm.section.guardian": "Encarregado de Educação (para menores)",
        "enrollmentForm.field.guardianName": "Nome do Encarregado",
        "enrollmentForm.field.guardianPhone": "Telefone do Encarregado",
        "enrollmentForm.field.enrollmentDate": "Data da Matrícula",
        "enrollmentForm.field.startDate": "Data de Início",
        "enrollmentForm.field.status": "Estado",
        "enrollmentForm.field.planType": "Tipo de Plano",
        "enrollmentForm.field.monthlyFee": "Mensalidade",
        "enrollmentForm.field.paymentDay": "Dia de Pagamento",
        "enrollmentForm.field.paymentMethod": "Forma de Pagamento",
        "enrollmentForm.field.contractSigned": "Contrato assinado",
        "enrollmentForm.field.contractDate": "Data de assinatura",
        "enrollmentForm.status.pending": "Pendente",
        "enrollmentForm.status.active": "Ativa",
        "enrollmentForm.status.cancelled": "Cancelada",
        "enrollmentForm.status.expired": "Expirada",
        "enrollmentForm.error.loading": "Erro ao carregar matrícula",
        "enrollmentForm.error.saving": "Erro ao guardar matrícula",
        "competitionForm.newTitle": "Nova Competição",
        "competitionForm.editTitle": "Editar Competição",
        "competitionForm.newSubtitle": "Preencha os dados e adicione os jogos",
        "competitionForm.editSubtitle": "Atualize os dados da competição",
        "competitionForm.section.info": "Informações da Competição",
        "competitionForm.section.results": "Resultado Final",
        "competitionForm.section.games": "Jogos",
        "competitionForm.field.name": "Nome",
        "competitionForm.field.type": "Tipo",
        "competitionForm.field.category": "Categoria",
        "competitionForm.field.season": "Temporada",
        "competitionForm.field.startDate": "Início",
        "competitionForm.field.endDate": "Fim",
        "competitionForm.field.status": "Estado",
        "competitionForm.field.organizer": "Organizador",
        "competitionForm.field.description": "Descrição",
        "competitionForm.stats.finalPosition": "Classificação Final",
        "competitionForm.stats.totalTeams": "Total de Equipas",
        "competitionForm.stats.title": "Estatísticas",
        "competitionForm.stats.wins": "Vitórias",
        "competitionForm.stats.draws": "Empates",
        "competitionForm.stats.losses": "Derrotas",
        "competitionForm.stats.goalsFor": "Golos Marcados",
        "competitionForm.stats.goalsAgainst": "Golos Sofridos",
        "competitionForm.game.add": "Adicionar Jogo",
        "competitionForm.game.empty": "Nenhum jogo registado",
        "competitionForm.game.emptyDesc": "Clique em \"Adicionar Jogo\" para começar",
        "competitionForm.game.round": "Jornada",
        "competitionForm.game.venue": "Recinto",
        "competitionForm.game.score": "Resultado",
        "competitionForm.error.loading": "Erro ao carregar competição",
        "competitionForm.error.saving": "Erro ao guardar competição",
        "competitionForm.error.nameRequired": "O nome da competição é obrigatório"
    }
};

function robustInsert(content, languageHeader, previousKey, newKeysObj) {
    const blockStart = content.indexOf(languageHeader);
    if (blockStart === -1) {
        console.error("Header " + languageHeader + " not found");
        return content;
    }
    
    const keyMatch = content.indexOf(previousKey, blockStart);
    if (keyMatch === -1) {
        console.error("Key " + previousKey + " not found after " + languageHeader);
        return content;
    }
    
    const eolIndex = content.indexOf('\\n', keyMatch);
    
    let newKeysStr = '';
    for (const [key, value] of Object.entries(newKeysObj)) {
        const safeValue = value.replace(/'/g, "\\\\'");
        newKeysStr += "\\n        '" + key + "': '" + safeValue + "',";
    }
    
    return content.slice(0, eolIndex + 1) + newKeysStr + content.slice(eolIndex + 1);
}

content = robustInsert(content, "'pt-BR': {", "'athleteForm.error.saving':", keysData["pt-BR"]);
content = robustInsert(content, "'en-US': {", "'athleteForm.error.saving':", keysData["en-US"]);
content = robustInsert(content, "'es-ES': {", "'athleteForm.error.saving':", keysData["es-ES"]);
content = robustInsert(content, "'fr-FR': {", "'athleteForm.error.saving':", keysData["fr-FR"]);
content = robustInsert(content, "'pt-PT': {", "'athleteForm.error.saving':", keysData["pt-PT"]);

fs.writeFileSync(contextPath, content, 'utf8');
console.log('Successfully added translation keys robustly to LanguageContext.tsx');
