const fs = require('fs');
const path = require('path');
const filePath = path.join(__dirname, '../contexts/LanguageContext.tsx');
let content = fs.readFileSync(filePath, 'utf8');

const target = `'pages.settings': 'Defini\u00e7\u00f5es do clube',
    },
};`;

const replacement = `'pages.settings': 'Defini\u00e7\u00f5es do clube',

        // Training Form
        'trainingForm.newTitle': 'Novo Treino',
        'trainingForm.editTitle': 'Editar Treino',
        'trainingForm.newSubtitle': 'Preencha os dados e adicione atletas e atividades',
        'trainingForm.editSubtitle': 'Atualize os dados do treino',
        'trainingForm.tab.general': 'Geral',
        'trainingForm.tab.athletes': 'Atletas',
        'trainingForm.tab.activities': 'Atividades',
        'trainingForm.section.dateTime': 'Data e Hora',
        'trainingForm.section.details': 'Detalhes do Treino',
        'trainingForm.section.description': 'Descri\u00e7\u00e3o e Observa\u00e7\u00f5es',
        'trainingForm.field.date': 'Data',
        'trainingForm.field.startTime': 'Hora de In\u00edcio',
        'trainingForm.field.endTime': 'Hora de Fim',
        'trainingForm.field.location': 'Local',
        'trainingForm.field.category': 'Categoria',
        'trainingForm.field.intensity': 'Intensidade',
        'trainingForm.field.focus': 'Foco Principal',
        'trainingForm.field.status': 'Estado',
        'trainingForm.field.select': 'Selecionar',
        'trainingForm.athletes.add': 'Adicionar Atletas',
        'trainingForm.athletes.selectCategory': 'Selecione uma categoria',
        'trainingForm.athletes.addCategory': 'Adicionar Categoria',
        'trainingForm.athletes.addIndividual': 'Adicionar Individual',
        'trainingForm.athletes.allAdded': 'Todos os atletas j\u00e1 foram adicionados',
        'trainingForm.athletes.attendanceList': 'Lista de Presen\u00e7a',
        'trainingForm.athletes.noAdded': 'Nenhum atleta adicionado',
        'trainingForm.athletes.useOptions': 'Adicione atletas usando as op\u00e7\u00f5es acima',
        'trainingForm.athletes.col.present': 'Presente',
        'trainingForm.athletes.col.performance': 'Desempenho',
        'trainingForm.athletes.col.effort': 'Esfor\u00e7o',
        'trainingForm.activities.title': 'Atividades do Treino',
        'trainingForm.activities.add': 'Adicionar Atividade',
        'trainingForm.activities.none': 'Nenhuma atividade registada',
        'trainingForm.activities.noneDesc': 'Adicione atividades para montar o plano do treino',
        'trainingForm.activities.addFirst': 'Adicionar Primeira Atividade',
        'trainingForm.activities.totalTime': 'Tempo Total',
        'trainingForm.activities.minutes': 'minutos',
        'trainingForm.activities.field.phase': 'Fase',
        'trainingForm.activities.field.name': 'Nome da Atividade',
        'trainingForm.activities.field.duration': 'Dura\u00e7\u00e3o (min)',
        'trainingForm.activities.field.description': 'Descri\u00e7\u00e3o (opcional)',
        'trainingForm.error.selectDate': 'Selecione uma data para o treino',
        'trainingForm.error.loading': 'Erro ao carregar dados',
        'trainingForm.error.saving': 'Erro ao guardar treino',
        'training.intensity.low': 'Baixa',
        'training.intensity.medium': 'M\u00e9dia',
        'training.intensity.high': 'Alta',
        'training.intensity.recovery': 'Regenerativo',
        'training.phase.warmup': 'Aquecimento',
        'training.phase.main': 'Principal',
        'training.phase.cooldown': 'Retorno \u00e0 Calma',
        'training.phase.tactical': 'T\u00e1tico',
        'training.phase.physical': 'F\u00edsico',
        'training.phase.technical': 'T\u00e9cnico',

        // Game Form
        'gameForm.newTitle': 'Novo Jogo',
        'gameForm.editTitle': 'Editar Jogo',
        'gameForm.newSubtitle': 'Preencha os dados e adicione os convocados',
        'gameForm.editSubtitle': 'Atualize os dados do jogo',
        'gameForm.tab.general': 'Geral',
        'gameForm.tab.lineup': 'Convocados',
        'gameForm.section.competition': 'Competi\u00e7\u00e3o e Ronda',
        'gameForm.section.matchup': 'Confronto',
        'gameForm.field.competition': 'Competi\u00e7\u00e3o',
        'gameForm.field.round': 'Ronda / Fase',
        'gameForm.field.status': 'Estado',
        'gameForm.field.date': 'Data',
        'gameForm.field.time': 'Hora',
        'gameForm.field.venue': 'Local',
        'gameForm.field.address': 'Morada',
        'gameForm.field.homeTeam': 'Equipa da Casa',
        'gameForm.field.awayTeam': 'Equipa Visitante',
        'gameForm.field.homeGame': 'Jogo em casa (somos a equipa anfitri\u00e3)',
        'gameForm.field.select': 'Selecionar',
        'gameForm.lineup.addPlayers': 'Adicionar Jogadores',
        'gameForm.lineup.related': 'Convocados',
        'gameForm.lineup.noPlayers': 'Nenhum jogador convocado',
        'gameForm.lineup.useOptions': 'Adicione jogadores usando as op\u00e7\u00f5es acima',
        'gameForm.lineup.col.player': 'Jogador',
        'gameForm.lineup.col.position': 'Posi\u00e7\u00e3o',
        'gameForm.lineup.col.starter': 'Titular',
        'gameForm.lineup.col.minutes': 'Min',
        'gameForm.lineup.selectCategory': 'Selecione uma categoria',
        'gameForm.lineup.addCategory': 'Adicionar Categoria',
        'gameForm.lineup.addIndividual': 'Adicionar Individual',
        'gameForm.lineup.allAdded': 'Todos os atletas j\u00e1 foram adicionados',
        'game.status.scheduled': 'Agendado',
        'game.status.inProgress': 'Em Andamento',
        'game.status.finished': 'Terminado',
        'game.status.postponed': 'Adiado',
        'game.status.cancelled': 'Cancelado',
        'gameForm.error.selectCompetition': 'Selecione uma competi\u00e7\u00e3o',
        'gameForm.error.loading': 'Erro ao carregar dados',
        'gameForm.error.saving': 'Erro ao guardar jogo',

        // Athlete Form
        'athleteForm.newTitle': 'Novo Atleta',
        'athleteForm.editTitle': 'Editar Atleta',
        'athleteForm.newSubtitle': 'Preencha os dados para cadastrar',
        'athleteForm.editSubtitle': 'Atualize as informa\u00e7\u00f5es do atleta',
        'athleteForm.tab.general': 'Geral',
        'athleteForm.tab.wardrobe': 'Rouparia',
        'athleteForm.tab.history': 'Hist\u00f3rico',
        'athleteForm.tab.physiology': 'Fisiologia',
        'athleteForm.photo': 'Foto do Atleta',
        'athleteForm.addPhoto': 'Adicionar foto',
        'athleteForm.changePhoto': 'Alterar foto',
        'athleteForm.section.personal': 'Informa\u00e7\u00f5es Pessoais',
        'athleteForm.section.address': 'Morada',
        'athleteForm.section.sports': 'Informa\u00e7\u00f5es Desportivas',
        'athleteForm.section.emergency': 'Contacto de Emerg\u00eancia',
        'athleteForm.section.guardian': 'Respons\u00e1vel (menores de idade)',
        'athleteForm.field.fullName': 'Nome Completo',
        'athleteForm.field.birthDate': 'Data de Nascimento',
        'athleteForm.field.cpf': 'NIF',
        'athleteForm.field.rg': 'CC',
        'athleteForm.field.phone': 'Telefone',
        'athleteForm.field.address': 'Morada',
        'athleteForm.field.city': 'Cidade',
        'athleteForm.field.state': 'Distrito',
        'athleteForm.field.zipCode': 'C\u00f3digo Postal',
        'athleteForm.field.position': 'Posi\u00e7\u00e3o',
        'athleteForm.field.dominantFoot': 'P\u00e9 Dominante',
        'athleteForm.field.jerseyNumber': 'N\u00famero de Camisola',
        'athleteForm.field.joinDate': 'Data de Entrada',
        'athleteForm.field.emergencyName': 'Nome',
        'athleteForm.field.relationship': 'Parentesco',
        'athleteForm.foot.right': 'Direito',
        'athleteForm.foot.left': 'Esquerdo',
        'athleteForm.foot.both': 'Ambidestro',
        'athleteForm.wardrobe.sizes': 'Tamanhos',
        'athleteForm.wardrobe.shirt': 'Camisola',
        'athleteForm.wardrobe.shorts': 'Calc\u00f5es',
        'athleteForm.wardrobe.cleats': 'Chuteiras',
        'athleteForm.wardrobe.uniformNumber': 'N\u00ba Uniforme',
        'athleteForm.wardrobe.delivered': 'Materiais Entregues',
        'athleteForm.wardrobe.uniform': 'Uniforme de Jogo',
        'athleteForm.wardrobe.trainingKit': 'Kit de Treino',
        'athleteForm.wardrobe.bag': 'Mochila/Saco',
        'athleteForm.wardrobe.deliveryDate': 'Data de Entrega',
        'athleteForm.wardrobe.notes': 'Observa\u00e7\u00f5es',
        'athleteForm.history.title': 'Hist\u00f3rico de Treinos e Jogos',
        'athleteForm.history.none': 'Nenhum hist\u00f3rico registado',
        'athleteForm.history.noneDesc': 'O hist\u00f3rico ser\u00e1 preenchido conforme o atleta participar em treinos e jogos.',
        'athleteForm.history.rating': 'Avalia\u00e7\u00e3o',
        'athleteForm.physiology.measurements': 'Medidas Corporais',
        'athleteForm.physiology.cardiovascular': 'Dados Cardiovasculares',
        'athleteForm.physiology.medical': 'Informa\u00e7\u00f5es M\u00e9dicas',
        'athleteForm.physiology.date': 'Data',
        'athleteForm.physiology.height': 'Altura (cm)',
        'athleteForm.physiology.weight': 'Peso (kg)',
        'athleteForm.physiology.bodyFat': '% Gordura',
        'athleteForm.physiology.bmi': 'IMC',
        'athleteForm.physiology.restingHR': 'FC Repouso (bpm)',
        'athleteForm.physiology.maxHR': 'FC M\u00e1xima (bpm)',
        'athleteForm.physiology.systolic': 'PA Sist\u00f3lica',
        'athleteForm.physiology.diastolic': 'PA Diast\u00f3lica',
        'athleteForm.physiology.bloodType': 'Tipo Sangu\u00edneo',
        'athleteForm.physiology.allergies': 'Alergias',
        'athleteForm.physiology.injuries': 'Les\u00f5es',
        'athleteForm.physiology.medicalNotes': 'Notas M\u00e9dicas',
        'athleteForm.error.nameRequired': 'O nome do atleta \u00e9 obrigat\u00f3rio',
        'athleteForm.error.loading': 'Erro ao carregar dados do atleta',
        'athleteForm.error.photoUpload': 'Erro ao fazer upload da foto',
        'athleteForm.error.saving': 'Erro ao guardar atleta',
    },
};`;

if (!content.includes(target)) {
    console.error('Target string not found in file!');
    process.exit(1);
}

const newContent = content.replace(target, replacement);
fs.writeFileSync(filePath, newContent, 'utf8');
console.log('Done! pt-PT keys added successfully.');
